version: '2'

services:

  afp_server:
    container_name: afp_server
    image: cptactionhank/netatalk:latest
    restart: always
    ports:
      - 548:548
    volumes:
      - /hostFolderToShare:/media/share/sharedFolderName
      - /hostFolderToShare2:/media/share/sharedFolderName2
    environment:
      - AFP_USER=myUsername
      - AFP_PASSWORD=${MY_SUPER_PASSWORD}
      - AFP_UID=1000
      - AFP_GID=1000
      - AVAHI=1
